# Generated by Django 5.1.4 on 2025-02-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastschool', models.CharField(max_length=100)),
                ('passedexam', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=50)),
                ('board_qualified', models.CharField(max_length=10)),
                ('admitcard', models.FileField(upload_to='admission_images')),
                ('studentname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=80)),
                ('fatheroccupation', models.CharField(max_length=80)),
                ('fatherannualincome', models.CharField(max_length=100)),
                ('mothername', models.CharField(max_length=80)),
                ('motheroccupation', models.CharField(max_length=80)),
                ('motherannualincome', models.CharField(max_length=100)),
                ('address1', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('postOffice', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('pincode', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('Select_sub', models.CharField(max_length=600)),
                ('stream', models.CharField(max_length=20)),
                ('hostel', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('stuPhoto', models.FileField(upload_to='admission_images')),
                ('status', models.CharField(choices=[('0', 'PENDING'), ('1', 'VERIFIED'), ('2', 'REJECTED')], default='0', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=800)),
                ('date_Added', models.DateTimeField()),
                ('downloadable', models.FileField(blank=True, null=True, upload_to='announcement_file')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Facultie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='faculity_images')),
                ('post', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Math', 'Math'), ('Biology', 'Biology'), ('Assamese', 'Assamese'), ('English', 'English'), ('Statistics', 'Statistics'), ('Economics', 'Economics'), ('Education', 'Education'), ('logicPhilosophy', ' logicPhilosophy'), ('Geography', 'Geography'), ('Arthopology', 'Arthopology'), ('Sociology', 'sociology'), ('poloticalScience', 'poloticalScience')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallary_image')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ss', models.FileField(upload_to='payment_ss')),
                ('Payment_verification', models.CharField(choices=[('1', 'verify'), ('2', 'rejected')], max_length=60)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
